name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_UPDATE_S3 }}
        aws-region: ${{ secrets.AWS_S3_WEBSITE_REGION }}

    - name: Deploy to S3
      run: aws s3 sync . s3://www.leematrading.com --delete
